In [5]:
import pandas as pd
df = pd.read_csv(
    "credit.csv",
    sep = ',',
    thousands = None,
    decimal = '.',
    encoding='latin-1')

In [7]:
df.head()

,checking_balance,months_loan_duration,credit_history,purpose,amount,savings_balance,employment_length,installment_rate,personal_status,other_debtors,...,property,age,installment_plan,housing,existing_credits,default,dependents,telephone,foreign_worker,job
0,< 0 DM,6,critical,radio/tv,1169,unknown,> 7 yrs,4,single male,none,...,real estate,67,none,own,2,1,1,yes,yes,skilled employee
1,1 - 200 DM,48,repaid,radio/tv,5951,< 100 DM,1 - 4 yrs,2,female,none,...,real estate,22,none,own,1,2,1,none,yes,skilled employee
2,unknown,12,critical,education,2096,< 100 DM,4 - 7 yrs,2,single male,none,...,real estate,49,none,own,1,1,2,none,yes,unskilled resident
3,< 0 DM,42,repaid,furniture,7882,< 100 DM,4 - 7 yrs,2,single male,guarantor,...,building society savings,45,none,for free,1,1,2,none,yes,skilled employee
4,< 0 DM,24,delayed,car (new),4870,< 100 DM,1 - 4 yrs,3,single male,none,...,unknown/none,53,none,for free,2,2,2,none,yes,skilled employee

In [10]:
%%writefile mapper_q1.py
#! /usr/bin/env python
import sys
if __name__ == "__main__":

    
    for line in sys.stdin:
        valor_columna=line.split(',')[2]
        
        
        
        sys.stdout.write("{}\t1\n".format(valor_columna))

Overwriting mapper_q1.py

In [11]:
!chmod +x mapper_q1.py
!cat ./credit.csv | ./mapper_q1.py | head

credit_history	1
critical	1
repaid	1
critical	1
repaid	1
delayed	1
repaid	1
repaid	1
repaid	1
repaid	1
Traceback (most recent call last):
  File "./mapper_q1.py", line 11, in <module>
    sys.stdout.write("{}\t1\n".format(valor_columna))
IOError: [Errno 32] Broken pipe

In [12]:
%%writefile reducer_q1.py
#!/usr/bin/env python

import sys

##
## Esta funcion reduce los elementos que
## tienen la misma clave
##

if __name__ == '__main__':

    curkey = None
    total = 0

    ##
    ## cada linea de texto recibida es una
    ## entrada clave \tabulador valor
    ##
    for line in sys.stdin:

        key, val = line.split("\t")
        val = int(val)

        if key == curkey:
            ##
            ## No se ha cambiado de clave. Aca se
            ## acumulan los valores para la misma clave.
            ##
            total += val
        else:
            ##
            ## Se cambio de clave. Se reinicia el
            ## acumulador.
            ##
            if curkey is not None:
                ##
                ## una vez se han reducido todos los elementos
                ## con la misma clave se imprime el resultado en
                ## el flujo de salida
                ##
                sys.stdout.write("{}\t{}\n".format(curkey, total))

            curkey = key
            total = val
     
    sys.stdout.write("{}\t{}\n".format(curkey, total))

Writing reducer_q1.py

In [13]:
!chmod +x reducer_q1.py
!cat ./credit.csv | ./mapper_q1.py | sort | ./reducer_q1.py | head

credit_history	1
critical	293
delayed	88
fully repaid	40
fully repaid this bank	49
repaid	530